"""add summary columns

Revision ID: 5a808cb0849e
Revises: ae09696070bb
Create Date: 2026-05-25 22:53:20.705634

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a808cb0849e"
down_revision: str | Sequence[str] | None = "ae09696070bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scores", sa.Column("summary", sa.String(length=2000), nullable=True))
    op.add_column(
        "scores", sa.Column("summary_generated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "summary_generated_at")
    op.drop_column("scores", "summary")
    # ### end Alembic commands ###
