"""add score_version column

Revision ID: ae09696070bb
Revises: 6227ed3a7a0d
Create Date: 2026-05-19 13:41:46.969041

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae09696070bb"
down_revision: str | Sequence[str] | None = "6227ed3a7a0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("score_version", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "score_version")
    # ### end Alembic commands ###
